name: 'project_2'
version: '1.0.0'
config-version: 2

profile: 'project_2'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  project_2:
    staging:
      +materialized: table
      +schema: public  # Use existing PUBLIC schema
    intermediate:
      +materialized: table
      +schema: public  # Use existing PUBLIC schema
    marts:
      +materialized: table
      +schema: public  # Use existing PUBLIC schema
    snapshots:
  retail_analytics:
    +materialized: table
    +schema: public